# Generated by Django 4.1 on 2022-08-30 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectcategory_project_slug_project_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name_plural': 'Project Categories'},
        ),
    ]
