# Generated by Django 4.1 on 2022-08-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_photogallery_status_videogallery_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photogallery',
            options={'verbose_name_plural': 'Photo Galleries'},
        ),
        migrations.AlterModelOptions(
            name='videogallery',
            options={'verbose_name_plural': 'Video Galleries'},
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='videogallery',
            name='caption',
            field=models.TextField(blank=True),
        ),
    ]
