# Generated by Django 4.1 on 2022-09-01 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featured',
            options={'verbose_name': 'Featured Article'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on'], 'verbose_name': 'Article'},
        ),
    ]
