# Generated by Django 4.1 on 2022-08-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='mdsmessage',
            options={'verbose_name': 'MDs Message'},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'verbose_name': 'Mission Statement'},
        ),
        migrations.AlterModelOptions(
            name='personel',
            options={'verbose_name': 'Personel'},
        ),
        migrations.RemoveField(
            model_name='mdsmessage',
            name='signature',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, help_text='Change to Publish for it to be seen'),
        ),
        migrations.AddField(
            model_name='mdsmessage',
            name='image',
            field=models.ImageField(blank=True, help_text='The picture shoulde be at least 512px by 512px and either .jpg or .png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mission',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, help_text='Change to Publish for it to be seen'),
        ),
        migrations.AddField(
            model_name='personel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personel',
            name='category',
            field=models.IntegerField(choices=[(0, 'Board of management'), (1, 'Leadership')], default=0, help_text='select Peronel membership title'),
        ),
        migrations.AlterField(
            model_name='personel',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Optional', max_length=50),
        ),
    ]
