# Generated by Django 4.1 on 2022-08-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='mdsmessage',
            options={'verbose_name': 'MDs Message'},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'verbose_name': 'Mission Statement'},
        ),
        migrations.AlterModelOptions(
            name='personel',
            options={'verbose_name': 'Personel'},
        ),
        migrations.AddField(
            model_name='aboutus',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, help_text='Change to Publish for it to be seen'),
        ),
        migrations.AddField(
            model_name='mission',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, help_text='Change to Publish for it to be seen'),
        ),
    ]
