# Generated by Django 4.1 on 2022-08-04 08:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_aboutus_options_alter_mdsmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='mdsmessage',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='statement',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='personel',
            name='category',
            field=models.IntegerField(choices=[(0, 'Board of management'), (1, 'Leadership')], default=0, help_text='select Peronel membership title'),
        ),
    ]
