# Generated by Django 4.1 on 2022-08-18 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_functions_objectives_vision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='functions',
            options={'verbose_name': 'Mandate & Functions'},
        ),
        migrations.AlterModelOptions(
            name='objectives',
            options={'verbose_name': 'Strategic Objectives'},
        ),
    ]
