# Generated by Django 4.1 on 2022-08-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_personel_description_alter_aboutus_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdsmessage',
            name='signature',
        ),
        migrations.AddField(
            model_name='mdsmessage',
            name='image',
            field=models.ImageField(blank=True, help_text='The picture shoulde be at least 512px by 512px and either .jpg or .png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='personel',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Optional', max_length=50),
        ),
    ]
