# Generated by Django 4.1 on 2022-08-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_functions_options_alter_objectives_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='image',
            field=models.ImageField(blank=True, help_text='The Image shoulde be at least 10px by 720px and either .jpg or .png', upload_to=''),
        ),
        migrations.AddField(
            model_name='vision',
            name='image',
            field=models.ImageField(blank=True, help_text='The Image shoulde be at least 10px by 720px and either .jpg or .png', upload_to=''),
        ),
    ]
