# Generated by Django 4.1 on 2022-08-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_mission_image_vision_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'Who We are', 'verbose_name_plural': 'Who We are'},
        ),
        migrations.AlterModelOptions(
            name='functions',
            options={'verbose_name': 'Mandate & Function'},
        ),
        migrations.AlterModelOptions(
            name='objectives',
            options={'verbose_name': 'Strategic Objective'},
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title',
            field=models.CharField(default='Who we are', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, help_text='Change to Publish for it to be seen'),
        ),
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, help_text='Change to Publish for it to be seen'),
        ),
        migrations.AlterField(
            model_name='functions',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, help_text='Change to Publish for it to be seen'),
        ),
        migrations.AlterField(
            model_name='mdsmessage',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, help_text='Change to Publish for it to be seen'),
        ),
        migrations.AlterField(
            model_name='mdsmessage',
            name='title',
            field=models.CharField(default='Message from mnagging Director', help_text="e.g. John's Message", max_length=200),
        ),
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, help_text='Change to Publish for it to be seen'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='title',
            field=models.CharField(default='Our Mission', max_length=200),
        ),
        migrations.AlterField(
            model_name='objectives',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, help_text='Change to Publish for it to be seen'),
        ),
        migrations.AlterField(
            model_name='personel',
            name='category',
            field=models.IntegerField(choices=[(0, 'Board of Directors'), (1, 'Management Team')], default=0, help_text='select Peronel membership title'),
        ),
        migrations.AlterField(
            model_name='personel',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, help_text='Change to Publish for it to be seen'),
        ),
        migrations.AlterField(
            model_name='vision',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, help_text='Change to Publish for it to be seen'),
        ),
        migrations.AlterField(
            model_name='vision',
            name='title',
            field=models.CharField(default='Our Vision', max_length=200),
        ),
    ]
