# Generated by Django 4.1 on 2022-08-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_aboutus_options_alter_functions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdsmessage',
            name='title',
            field=models.CharField(default='Message from the Managing Director', help_text="e.g. John's Message", max_length=200),
        ),
    ]
