# Generated by Django 4.1 on 2022-08-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_alter_mdsmessage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdsmessage',
            name='image',
            field=models.ImageField(blank=True, help_text='The profile picture shoulde be at least 512px by 512px and either .jpg or .png', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='image',
            field=models.ImageField(blank=True, help_text='The Image shoulde be at least 10px by 720px and either .jpg or .png', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='vision',
            name='image',
            field=models.ImageField(blank=True, help_text='The Image shoulde be at least 10px by 720px and either .jpg or .png', upload_to='media'),
        ),
    ]
