# Generated by Django 4.1 on 2022-08-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_mdsmessage_image_alter_mission_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdsmessage',
            name='image',
            field=models.ImageField(help_text='picture shoulde be at least 512px by 512px and either .jpg or .png', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='mdsmessage',
            name='position',
            field=models.CharField(default='Managing Director', max_length=50),
        ),
        migrations.AlterField(
            model_name='mdsmessage',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, help_text='Change to Published for it to be seen'),
        ),
    ]
