# Generated by Django 4.1 on 2022-08-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_alter_mdsmessage_image_alter_mdsmessage_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='image',
        ),
        migrations.RemoveField(
            model_name='vision',
            name='image',
        ),
    ]
