# Generated by Django 4.1 on 2022-08-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_remove_mission_image_remove_vision_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCharter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Service Charter', max_length=200)),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, help_text='Change to Publish for it to be seen')),
            ],
        ),
    ]
