# Generated by Django 4.1 on 2022-08-29 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_servicecharter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'verbose_name': 'Our Mission', 'verbose_name_plural': 'Our Mission'},
        ),
        migrations.AlterModelOptions(
            name='servicecharter',
            options={'verbose_name_plural': 'Service charter'},
        ),
        migrations.AlterModelOptions(
            name='vision',
            options={'verbose_name': 'Our Vision', 'verbose_name_plural': 'Our Vision'},
        ),
    ]
