# Generated by Django 4.1 on 2022-08-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_alter_mission_options_alter_servicecharter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectives',
            name='file',
            field=models.FileField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='objectives',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
