# Generated by Django 4.1 on 2022-09-01 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_objectives_file_alter_objectives_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectives',
            options={'verbose_name': 'Strategic Plan', 'verbose_name_plural': 'Strategic Plan'},
        ),
        migrations.AddField(
            model_name='objectives',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='servicecharter',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='servicecharter',
            name='file',
            field=models.FileField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='objectives',
            name='title',
            field=models.CharField(default='Strategic Plan', max_length=200),
        ),
    ]
