# Generated by Django 4.1 on 2022-09-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_alter_objectives_options_objectives_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecharter',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
