# Generated by Django 4.1 on 2022-09-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0016_alter_corevalue_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChairPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, help_text='Optional', max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Image size should be in .jpg or .png', null=True, upload_to='media')),
                ('category', models.IntegerField(choices=[(0, 'Board of Directors'), (1, 'Management Team')], default=0, help_text='select Peronel membership title')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, help_text='Change to Publish for it to be seen')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ChairPerson',
                'verbose_name_plural': 'ChairPerson',
            },
        ),
    ]
