# Generated by Django 4.1 on 2022-08-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('job_ID', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=200)),
                ('job_description', models.TextField()),
                ('resposibilities', models.TextField()),
                ('qualification', models.TextField()),
                ('advert_file', models.FileField(blank=True, upload_to='media')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Date Published')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, help_text='Change to Publish for it to be seen')),
                ('job_type', models.IntegerField(choices=[(0, 'Full Time'), (1, 'Part Time'), (2, 'Internship'), (3, 'Attachment')], default=0, help_text='Choose the appropriate job type to advertise')),
            ],
            options={
                'verbose_name': 'Job Advert',
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ref_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='media')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, help_text='Change to Publish for it to be seen')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
