# Generated by Django 4.1 on 2022-08-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_alter_jobadvert_status_alter_tender_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='tender_status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=20),
        ),
    ]
