# Generated by Django 4.1 on 2022-08-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_tender_tender_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobadvert',
            name='job_type',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Attachment', 'Attachment')], default='Contract', help_text='Choose the appropriate job type to advertise', max_length=200),
        ),
    ]
