# Generated by Django 4.1 on 2022-09-07 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0005_jobadvert_deadline_jobadvert_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobadvert',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='deadline for application'),
        ),
    ]
