# Generated by Django 4.1 on 2022-08-04 08:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltoactionpanel',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patner',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
