# Generated by Django 4.1 on 2022-08-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_carousel_caption_alter_carousel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patner',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
