# Generated by Django 4.1 on 2022-08-16 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobAdvert',
        ),
        migrations.DeleteModel(
            name='Tender',
        ),
    ]
