# Generated by Django 4.1 on 2022-08-04 08:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_faq_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('job_ID', models.CharField(max_length=50)),
                ('job_description', ckeditor.fields.RichTextField()),
                ('resposibilities', ckeditor.fields.RichTextField()),
                ('qualification', ckeditor.fields.RichTextField()),
                ('advert_file', models.FileField(upload_to='media')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='media')),
                ('category', models.IntegerField(choices=[(0, 'default'), (1, 'advertisement')], default=0)),
            ],
        ),
    ]
