# Generated by Django 4.1 on 2022-08-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_faq_status_alter_publication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Privacy Policy', max_length=200)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='media')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, help_text='change to published to be seen')),
            ],
        ),
        migrations.CreateModel(
            name='terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Terms of Service', max_length=200)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='media')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, help_text='change to published to be seen')),
            ],
        ),
    ]
