# Generated by Django 4.1 on 2022-08-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_privacy_terms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacy',
            options={'verbose_name': 'Privacy Policy', 'verbose_name_plural': 'Privacy Policy'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'Resource'},
        ),
        migrations.AlterModelOptions(
            name='terms',
            options={'verbose_name': 'Terms of Service', 'verbose_name_plural': 'Terms of Service'},
        ),
    ]
