# Generated by Django 4.1 on 2022-08-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_jobadvert_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobadvert',
            name='job_type',
            field=models.IntegerField(choices=[(0, 'Fulltime'), (1, 'Parttime'), (2, 'Internship'), (3, 'Attachment')], default=0, help_text='Choose the appropriate job type to advertise'),
        ),
        migrations.AddField(
            model_name='jobadvert',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, help_text='Change to Publish for it to be seen'),
        ),
    ]
