# Generated by Django 4.1 on 2022-08-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_jobadvert_job_type_jobadvert_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobadvert',
            name='slug',
            field=models.SlugField(default=12, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobadvert',
            name='advert_file',
            field=models.FileField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='jobadvert',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date Published'),
        ),
    ]
